import { CodmTeam, CodmRound, CodmTournamentSettings } from '../types/codm';

export const CODM_MAPS = ['Isolated', 'Blackout', 'Krai'];

export const INITIAL_CODM_SETTINGS: CodmTournamentSettings = {
  title: 'CALL OF DUTY: MOBILE – BATTLE ROYALE',
  subtitle: 'Squad Mode • 8 Teams • 4 Rounds • Online Custom Lobby',
  gameMode: 'Battle Royale – Squad',
  totalMatches: 4,
  totalTeams: 8,
  statusBadge: 'LIVE',
  dateText: 'TBA',
  pointsPerKill: 1,
  logoUrl: '',
  adminPasscode: 'admin123',
};

export const INITIAL_CODM_TEAMS: CodmTeam[] = [
  {
    id: 'ct_1',
    name: 'Criminology Bulls',
    tag: 'BSCJ',
    seed: 1,
    avatarColor: '#ef4444',
    avatarIcon: '🐂',
    players: [
      { id: 'p_1_1', name: 'Player 1', ign: 'BSCJ-Ace', role: 'main' },
      { id: 'p_1_2', name: 'Player 2', ign: 'BSCJ-Reaper', role: 'main' },
      { id: 'p_1_3', name: 'Player 3', ign: 'BSCJ-Ghost', role: 'main' },
      { id: 'p_1_4', name: 'Player 4', ign: 'BSCJ-Viper', role: 'main' },
      { id: 'p_1_5', name: 'Player 5 (Sub)', ign: 'BSCJ-Shadow', role: 'reserve' },
    ],
  },
  {
    id: 'ct_2',
    name: 'Hospitality Titans',
    tag: 'BSHM',
    seed: 2,
    avatarColor: '#8b5cf6',
    avatarIcon: '👑',
    players: [
      { id: 'p_2_1', name: 'Player 1', ign: 'BSHM-Titan', role: 'main' },
      { id: 'p_2_2', name: 'Player 2', ign: 'BSHM-Chef', role: 'main' },
      { id: 'p_2_3', name: 'Player 3', ign: 'BSHM-Nova', role: 'main' },
      { id: 'p_2_4', name: 'Player 4', ign: 'BSHM-Apex', role: 'main' },
      { id: 'p_2_5', name: 'Player 5 (Sub)', ign: 'BSHM-Reserve', role: 'reserve' },
    ],
  },
  {
    id: 'ct_3',
    name: 'Purple Orca',
    tag: 'BECED',
    seed: 3,
    avatarColor: '#a855f7',
    avatarIcon: '🐋',
    players: [
      { id: 'p_3_1', name: 'Player 1', ign: 'BECED-Orca1', role: 'main' },
      { id: 'p_3_2', name: 'Player 2', ign: 'BECED-Wave', role: 'main' },
      { id: 'p_3_3', name: 'Player 3', ign: 'BECED-Tide', role: 'main' },
      { id: 'p_3_4', name: 'Player 4', ign: 'BECED-Storm', role: 'main' },
      { id: 'p_3_5', name: 'Player 5 (Sub)', ign: 'BECED-Sub', role: 'reserve' },
    ],
  },
  {
    id: 'ct_4',
    name: 'Blazing Phoenix',
    tag: 'BEED',
    seed: 4,
    avatarColor: '#f59e0b',
    avatarIcon: '🔥',
    players: [
      { id: 'p_4_1', name: 'Player 1', ign: 'BEED-Ignite', role: 'main' },
      { id: 'p_4_2', name: 'Player 2', ign: 'BEED-Flare', role: 'main' },
      { id: 'p_4_3', name: 'Player 3', ign: 'BEED-Blaze', role: 'main' },
      { id: 'p_4_4', name: 'Player 4', ign: 'BEED-Ash', role: 'main' },
      { id: 'p_4_5', name: 'Player 5 (Sub)', ign: 'BEED-Reserve', role: 'reserve' },
    ],
  },
  {
    id: 'ct_5',
    name: 'Strength Resurgence',
    tag: 'BAP',
    seed: 5,
    avatarColor: '#6366f1',
    avatarIcon: '🛡️',
    players: [
      { id: 'p_5_1', name: 'Player 1', ign: 'BAP-Aegis', role: 'main' },
      { id: 'p_5_2', name: 'Player 2', ign: 'BAP-Iron', role: 'main' },
      { id: 'p_5_3', name: 'Player 3', ign: 'BAP-Fort', role: 'main' },
      { id: 'p_5_4', name: 'Player 4', ign: 'BAP-Shield', role: 'main' },
      { id: 'p_5_5', name: 'Player 5 (Sub)', ign: 'BAP-Reserve', role: 'reserve' },
    ],
  },
  {
    id: 'ct_6',
    name: 'Silver Wolves',
    tag: 'BPA',
    seed: 6,
    avatarColor: '#64748b',
    avatarIcon: '🐺',
    players: [
      { id: 'p_6_1', name: 'Player 1', ign: 'BPA-Alpha', role: 'main' },
      { id: 'p_6_2', name: 'Player 2', ign: 'BPA-Fang', role: 'main' },
      { id: 'p_6_3', name: 'Player 3', ign: 'BPA-Howl', role: 'main' },
      { id: 'p_6_4', name: 'Player 4', ign: 'BPA-Shadow', role: 'main' },
      { id: 'p_6_5', name: 'Player 5 (Sub)', ign: 'BPA-Pack', role: 'reserve' },
    ],
  },
  {
    id: 'ct_7',
    name: 'Apex Hornets',
    tag: 'BSEntrep',
    seed: 7,
    avatarColor: '#eab308',
    avatarIcon: '🐝',
    players: [
      { id: 'p_7_1', name: 'Player 1', ign: 'ENT-Stinger', role: 'main' },
      { id: 'p_7_2', name: 'Player 2', ign: 'ENT-Swarm', role: 'main' },
      { id: 'p_7_3', name: 'Player 3', ign: 'ENT-Buzz', role: 'main' },
      { id: 'p_7_4', name: 'Player 4', ign: 'ENT-Hive', role: 'main' },
      { id: 'p_7_5', name: 'Player 5 (Sub)', ign: 'ENT-Reserve', role: 'reserve' },
    ],
  },
  {
    id: 'ct_8',
    name: 'Tech Python',
    tag: 'BSIT',
    seed: 8,
    avatarColor: '#10b981',
    avatarIcon: '🐍',
    players: [
      { id: 'p_8_1', name: 'Player 1', ign: 'BSIT-Python', role: 'main' },
      { id: 'p_8_2', name: 'Player 2', ign: 'BSIT-Byte', role: 'main' },
      { id: 'p_8_3', name: 'Player 3', ign: 'BSIT-Cipher', role: 'main' },
      { id: 'p_8_4', name: 'Player 4', ign: 'BSIT-Glitch', role: 'main' },
      { id: 'p_8_5', name: 'Player 5 (Sub)', ign: 'BSIT-Reserve', role: 'reserve' },
    ],
  },
];

export const INITIAL_CODM_ROUNDS: CodmRound[] = [
  {
    roundNumber: 1,
    name: 'Match 1',
    lobbyType: 'Online Custom Lobby',
    map: 'Isolated',
    status: 'scheduled',
    results: {},
  },
  {
    roundNumber: 2,
    name: 'Match 2',
    lobbyType: 'Online Custom Lobby',
    map: 'Blackout',
    status: 'scheduled',
    results: {},
  },
  {
    roundNumber: 3,
    name: 'Match 3',
    lobbyType: 'Online Custom Lobby',
    map: 'Isolated',
    status: 'scheduled',
    results: {},
  },
  {
    roundNumber: 4,
    name: 'Match 4',
    lobbyType: 'Online Custom Lobby',
    map: 'Blackout',
    status: 'scheduled',
    results: {},
  },
];
